on: [push]

env:
  MACHINE: rpi3

jobs:
  build-os:
    runs-on: ubuntu-latest
    name: Build NULIX OS with custom apps
    steps:
      - name: Checkout compose file
        uses: actions/checkout@v4
        with:
          sparse-checkout: docker-compose.yml
      - name: Fetch base NULIX OS
        uses: nulix/os-build-with-apps@v0.9.9
        with:
          step_name: fetch-base-os
          machine: ${{ env.MACHINE }}
      - name: Inject custom apps
        uses: nulix/os-build-with-apps@v0.9.9
        with:
          step_name: inject-apps
          machine: ${{ env.MACHINE }}
      - name: Build OS image
        uses: nulix/os-build-with-apps@v0.9.9
        with:
          step_name: build-os-image
          machine: ${{ env.MACHINE }}
      - name: Upload OS image
        uses: actions/upload-artifact@v4
        with:
          name: nulix-os-${{ env.MACHINE }}-v${{ env.NULIX_OS_VER }}
          path: nulix-os/build/deploy/${{ env.MACHINE }}/nulix-os-${{ env.NULIX_OS_VER }}.img.bz2
          retention-days: 7  # Keep the artifact for 7 days
